In [ ]:
# Carregando dataset
import kagglehub as kh
import polars as pl

path = kh.dataset_download("akshaypawar7/millions-of-movies")

lf = pl.scan_csv(f"{path}/movies.csv")

print(lf.select("title").limit(5).collect())

c:\Users\gabri\pipeline_avaliacao_filmes\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\gabri\.cache\kagglehub\datasets\akshaypawar7\millions-of-movies\911.archive...

100%|██████████| 164M/164M [01:32<00:00, 1.87MB/s]

Extracting files...
shape: (5, 1)
┌─────────────────────────────────┐
│ title                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Meg 2: The Trench               │
│ The Pope's Exorcist             │
│ Deadpool & Wolverine            │
│ Transformers: Rise of the Beas… │
│ Dune: Part Two                  │
└─────────────────────────────────┘

In [8]:
lf.columns

C:\Users\gabri\AppData\Local\Temp\ipykernel_988\3701027225.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  lf.columns

['id',
 'title',
 'genres',
 'original_language',
 'overview',
 'popularity',
 'production_companies',
 'release_date',
 'budget',
 'revenue',
 'runtime',
 'status',
 'tagline',
 'vote_average',
 'vote_count',
 'credits',
 'keywords',
 'poster_path',
 'backdrop_path',
 'recommendations']

In [10]:
lf.select("id").limit(5).collect()

shape: (5, 1)
┌────────┐
│ id     │
│ ---    │
│ i64    │
╞════════╡
│ 615656 │
│ 758323 │
│ 533535 │
│ 667538 │
│ 693134 │
└────────┘

In [12]:
# Contar quantos filmes tem ao total
print(lf.select(pl.count()).collect())

C:\Users\gabri\AppData\Local\Temp\ipykernel_988\1851663287.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  print(lf.select(pl.count()).collect())

shape: (1, 1)
┌────────┐
│ count  │
│ ---    │
│ u32    │
╞════════╡
│ 722317 │
└────────┘

In [14]:
import polars as pl
import os

df = pl.read_parquet(
    "s3://movies/bronze/movie_titles.parquet",
    storage_options={
        "aws_access_key_id": "admin",
        "aws_secret_access_key": "admin123",
        "aws_endpoint_url": "http://localhost:9000",
    }
)

df.head()

shape: (5, 24)
┌───────┬───────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ index ┆ budget    ┆ genres     ┆ homepage   ┆ … ┆ vote_count ┆ cast      ┆ crew      ┆ director  │
│ ---   ┆ ---       ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ i64   ┆ i64       ┆ str        ┆ str        ┆   ┆ i64        ┆ str       ┆ str       ┆ str       │
╞═══════╪═══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0     ┆ 237000000 ┆ Action     ┆ http://www ┆ … ┆ 11800      ┆ Sam Worth ┆ [{'name': ┆ James     │
│       ┆           ┆ Adventure  ┆ .avatarmov ┆   ┆            ┆ ington    ┆ 'Stephen  ┆ Cameron   │
│       ┆           ┆ Fantasy    ┆ ie.com/    ┆   ┆            ┆ Zoe       ┆ E.        ┆           │
│       ┆           ┆ Scien…     ┆            ┆   ┆            ┆ Saldana   ┆ Rivkin',… ┆           │
│       ┆           ┆            ┆            ┆   ┆            ┆ Si…       ┆           ┆           │
│ 1     ┆ 300000000 ┆ Adventure  ┆ http://dis ┆ … ┆ 4500       ┆ Johnny    ┆ [{'name': ┆ Gore      │
│       ┆           ┆ Fantasy    ┆ ney.go.com ┆   ┆            ┆ Depp      ┆ 'Dariusz  ┆ Verbinski │
│       ┆           ┆ Action     ┆ /disneypic ┆   ┆            ┆ Orlando   ┆ Wolski',  ┆           │
│       ┆           ┆            ┆ …          ┆   ┆            ┆ Bloom     ┆ 'g…       ┆           │
│       ┆           ┆            ┆            ┆   ┆            ┆ Keir…     ┆           ┆           │
│ 2     ┆ 245000000 ┆ Action     ┆ http://www ┆ … ┆ 4466       ┆ Daniel    ┆ [{'name': ┆ Sam       │
│       ┆           ┆ Adventure  ┆ .sonypictu ┆   ┆            ┆ Craig     ┆ 'Thomas   ┆ Mendes    │
│       ┆           ┆ Crime      ┆ res.com/mo ┆   ┆            ┆ Christoph ┆ Newman',  ┆           │
│       ┆           ┆            ┆ …          ┆   ┆            ┆ Waltz L…  ┆ 'ge…      ┆           │
│ 3     ┆ 250000000 ┆ Action     ┆ http://www ┆ … ┆ 9106       ┆ Christian ┆ [{'name': ┆ Christoph │
│       ┆           ┆ Crime      ┆ .thedarkkn ┆   ┆            ┆ Bale      ┆ 'Hans     ┆ er Nolan  │
│       ┆           ┆ Drama      ┆ ightrises. ┆   ┆            ┆ Michael   ┆ Zimmer',  ┆           │
│       ┆           ┆ Thriller   ┆ …          ┆   ┆            ┆ Caine G…  ┆ 'gend…    ┆           │
│ 4     ┆ 260000000 ┆ Action     ┆ http://mov ┆ … ┆ 2124       ┆ Taylor    ┆ [{'name': ┆ Andrew    │
│       ┆           ┆ Adventure  ┆ ies.disney ┆   ┆            ┆ Kitsch    ┆ 'Andrew   ┆ Stanton   │
│       ┆           ┆ Science    ┆ .com/john- ┆   ┆            ┆ Lynn      ┆ Stanton', ┆           │
│       ┆           ┆ Ficti…     ┆ …          ┆   ┆            ┆ Collins   ┆ 'g…       ┆           │
│       ┆           ┆            ┆            ┆   ┆            ┆ Sam…      ┆           ┆           │
└───────┴───────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘